name: Deploy To Production

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      # Configure AWS for ECR login. Getting secrets from Github Secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      # Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build fresh images for ECR, tag with new version and push
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: whatshafiz_php-fpm
          IMAGE_TAG: 'staging-latest'
        run: |
          docker build -t whatshafiz_php-fpm:$IMAGE_TAG ./src --file=./src/Dockerfile.prod
          docker tag whatshafiz_php-fpm:$IMAGE_TAG $ECR_REGISTRY/whatshafiz_php-fpm:$IMAGE_TAG
          docker push $ECR_REGISTRY/whatshafiz_php-fpm:$IMAGE_TAG

      # Generate deployment package for EB
      - name: Generate deployment package
        env:
          IMAGE_TAG: 'staging-latest'
        run: |
          sed -i -e "s/amazonaws.com\/whatshafiz_php-fpm.*\"/amazonaws.com\/whatshafiz_php-fpm:$IMAGE_TAG\"/g" ./docker-compose.yml
          zip deploy.zip docker-compose.yml .ebextensions/* .platform/* src/docker/* -r

      # Generate unique build id for EB
      - name: 'Set build id'
        id: build_id
        # add a step output `steps.build_id.outputs.id` as the unique id
        run: echo "::set-output name=id::$(date +%s)"

      # Deploy to EB
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v10
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: whatshafiz
          environment_name: whatshafiz-env
          deployment_package: deploy.zip
          version_label: staging-latest-${{ steps.build_id.outputs.id }}
          region: eu-west-1

      # Logout from ECR
      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
